### PR TITLE
Starting to fix the integration of TC and Arq

### PR DESCRIPTION
**Pull request by poikilotherm**
Hi @hantsy,

I started to look a bit into this, seeing you folks [chatting here](https://github.com/arquillian/arquillian-core/issues/388). (Context: I'm trying to get some stuff going for Payara & Dataverse https://github.com/IQSS/dataverse/issues/9237)

This does not fix all the issues, but at least I see some logs and containers getting started.

The errors I still see might be worth taking to the Testcontaines folks Slack, maybe @kiview @bsideup can help us out? (So I don't post them here for now.)

Let me know what you think :smile_cat: 

Best,
Oliver

### CODE REVIEW

**Comment by hantsy** [comment]
@poikilotherm  Thanks you every much. I will check the code change details.

**Comment by hantsy** [comment]
After simple exploring the codes, I found the `AutomaticDeployment` is removed. I am not sure in the current code, how to ensure the tc-based WildFly is 100% running successfully and all ports are available and ready for clients.  In the original `AutomaticDeployment` service registration which allow to do some modification on the deployment unit in a `@BeforeDeployment` method.

**Comment by poikilotherm** [comment]
I had some very strange error with the auto deployment, which is why I removed it.

Please note: both Arquillian and Testcontainers use the JUnit Jupiter `BeforeAllCallback` interface to hook into the test startup phase. The order is important - JUnit guarantees sequential execution of these callback from outmost extension to the most inner `@BeforeAll` method.

The TC extension starts the containers and **blocks** until the startup and wait strategies are succeeding. Only then Arquillian will kick in! Which means if we need to wait for something more specific, we need to define a better waiting strategy in `WildflyContainer` as default. We can set it in the test class for experimentation if necessary.

**Comment by hantsy** [comment]
Thank you all. I have merged this pr into the main branch and replace the original codes, and refresh the codes.

Hope there are some updates to simplify the testcontaiers integration as provided by spring boot in the arquillian core project, waiting for the updates of https://github.com/arquillian/arquillian-core/issues/388

**Pull request merged**
